// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _8: x0 => x0.arrayBuffer(),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _17: (x0,x1) => x0.get(x1),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _215: () => new Array(),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _770: x0 => x0.firstElementChild,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _919: x0 => x0.headers,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1089: (x0,x1) => x0.getContext(x1),
      _1091: x0 => x0.convertToBlob(),
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1286: (x0,x1) => x0.createElement(x1),
      _1292: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1293: () => globalThis.window.navigator.userAgent,
      _1295: (x0,x1) => x0.initialize(x1),
      _1296: (x0,x1) => x0.initTokenClient(x1),
      _1297: (x0,x1) => x0.initCodeClient(x1),
      _1299: (x0,x1) => x0.warn(x1),
      _1300: x0 => x0.disableAutoSelect(),
      _1301: (x0,x1) => x0.querySelector(x1),
      _1302: (x0,x1) => x0.getAttribute(x1),
      _1303: (x0,x1) => x0.createElement(x1),
      _1304: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _1305: (x0,x1) => x0.append(x1),
      _1306: x0 => x0.remove(),
      _1307: (x0,x1) => x0.removeItem(x1),
      _1308: (x0,x1) => x0.getItem(x1),
      _1309: (x0,x1,x2) => x0.setItem(x1,x2),
      _1311: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1312: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1317: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1318: (x0,x1) => x0.canShare(x1),
      _1319: (x0,x1) => x0.share(x1),
      _1321: (x0,x1,x2) => ({files: x0,title: x1,text: x2}),
      _1322: (x0,x1) => ({files: x0,text: x1}),
      _1323: (x0,x1) => ({files: x0,title: x1}),
      _1324: x0 => ({files: x0}),
      _1325: (x0,x1) => ({title: x0,text: x1}),
      _1327: x0 => x0.click(),
      _1328: () => ({}),
      _1329: (x0,x1,x2) => new File(x0,x1,x2),
      _1330: () => globalThis.Notification.requestPermission(),
      _1331: x0 => globalThis.URL.revokeObjectURL(x0),
      _1332: (x0,x1,x2,x3) => x0.drawImage(x1,x2,x3),
      _1333: (x0,x1,x2,x3,x4,x5) => x0.drawImage(x1,x2,x3,x4,x5),
      _1334: x0 => globalThis.URL.createObjectURL(x0),
      _1335: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1335(f,arguments.length,x0) }),
      _1336: (x0,x1,x2,x3) => x0.toBlob(x1,x2,x3),
      _1337: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1337(f,arguments.length,x0) }),
      _1338: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1338(f,arguments.length,x0) }),
      _1339: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1339(f,arguments.length,x0) }),
      _1340: (x0,x1) => x0.replaceChildren(x1),
      _1341: x0 => x0.disconnect(),
      _1342: x0 => x0.disconnect(),
      _1343: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1343(f,arguments.length,x0,x1) }),
      _1344: x0 => new ResizeObserver(x0),
      _1345: (x0,x1) => x0.observe(x1),
      _1346: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1346(f,arguments.length,x0,x1) }),
      _1347: x0 => new MutationObserver(x0),
      _1348: x0 => ({childList: x0}),
      _1349: (x0,x1,x2) => x0.observe(x1,x2),
      _1350: (x0,x1) => x0.item(x1),
      _1351: x0 => ({audio: x0}),
      _1352: (x0,x1) => x0.getUserMedia(x1),
      _1353: x0 => x0.getAudioTracks(),
      _1354: x0 => x0.stop(),
      _1355: (x0,x1) => x0.removeTrack(x1),
      _1356: x0 => x0.close(),
      _1357: x0 => x0.getSettings(),
      _1358: x0 => ({sampleRate: x0}),
      _1359: x0 => new AudioContext(x0),
      _1360: () => new AudioContext(),
      _1361: x0 => x0.suspend(),
      _1362: x0 => x0.resume(),
      _1363: (x0,x1) => x0.connect(x1),
      _1364: (x0,x1) => x0.createMediaStreamSource(x1),
      _1365: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1365(f,arguments.length,x0) }),
      _1366: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1366(f,arguments.length,x0) }),
      _1367: (x0,x1) => x0.addModule(x1),
      _1368: x0 => ({parameterData: x0}),
      _1369: (x0,x1,x2) => new AudioWorkletNode(x0,x1,x2),
      _1375: x0 => x0.pause(),
      _1376: x0 => x0.resume(),
      _1377: x0 => x0.disconnect(),
      _1378: x0 => x0.stop(),
      _1379: (x0,x1,x2) => ({mimeType: x0,audioBitsPerSecond: x1,bitsPerSecond: x2}),
      _1380: (x0,x1) => new MediaRecorder(x0,x1),
      _1381: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1381(f,arguments.length,x0) }),
      _1382: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1382(f,arguments.length,x0) }),
      _1383: (x0,x1) => x0.start(x1),
      _1384: x0 => ({type: x0}),
      _1385: (x0,x1) => new Blob(x0,x1),
      _1386: (x0,x1) => globalThis.jsFixWebmDuration(x0,x1),
      _1387: x0 => x0.createAnalyser(),
      _1388: (x0,x1) => x0.getFloatFrequencyData(x1),
      _1389: x0 => globalThis.MediaRecorder.isTypeSupported(x0),
      _1390: x0 => x0.decode(),
      _1391: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1392: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1393: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1393(f,arguments.length,x0) }),
      _1394: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1394(f,arguments.length,x0) }),
      _1395: x0 => x0.send(),
      _1396: () => new XMLHttpRequest(),
      _1397: (x0,x1) => x0.createMediaElementSource(x1),
      _1398: x0 => x0.createStereoPanner(),
      _1399: x0 => x0.load(),
      _1400: x0 => x0.play(),
      _1401: x0 => x0.pause(),
      _1403: x0 => ({video: x0}),
      _1404: x0 => x0.getVideoTracks(),
      _1405: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1405(f,arguments.length,x0) }),
      _1406: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1406(f,arguments.length,x0) }),
      _1407: (x0,x1,x2) => x0.getCurrentPosition(x1,x2),
      _1410: () => globalThis.firebase_core.getApps(),
      _1411: (x0,x1,x2,x3,x4,x5,x6,x7) => ({apiKey: x0,authDomain: x1,databaseURL: x2,projectId: x3,storageBucket: x4,messagingSenderId: x5,measurementId: x6,appId: x7}),
      _1412: (x0,x1) => globalThis.firebase_core.initializeApp(x0,x1),
      _1413: x0 => globalThis.firebase_core.getApp(x0),
      _1414: () => globalThis.firebase_core.getApp(),
      _1415: (x0,x1,x2) => globalThis.firebase_core.registerVersion(x0,x1,x2),
      _1441: () => globalThis.firebase_core.SDK_VERSION,
      _1447: x0 => x0.apiKey,
      _1449: x0 => x0.authDomain,
      _1451: x0 => x0.databaseURL,
      _1453: x0 => x0.projectId,
      _1455: x0 => x0.storageBucket,
      _1457: x0 => x0.messagingSenderId,
      _1459: x0 => x0.measurementId,
      _1461: x0 => x0.appId,
      _1463: x0 => x0.name,
      _1464: x0 => x0.options,
      _1465: (x0,x1) => x0.debug(x1),
      _1466: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1466(f,arguments.length,x0) }),
      _1467: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1467(f,arguments.length,x0,x1) }),
      _1468: (x0,x1) => ({createScript: x0,createScriptURL: x1}),
      _1469: (x0,x1,x2) => x0.createPolicy(x1,x2),
      _1470: (x0,x1) => x0.createScriptURL(x1),
      _1471: (x0,x1,x2) => x0.createScript(x1,x2),
      _1472: (x0,x1) => x0.appendChild(x1),
      _1473: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1473(f,arguments.length,x0) }),
      _1474: (x0,x1) => x0.item(x1),
      _1475: () => new FileReader(),
      _1477: (x0,x1) => x0.readAsArrayBuffer(x1),
      _1478: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1478(f,arguments.length,x0) }),
      _1479: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _1480: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1480(f,arguments.length,x0) }),
      _1481: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1482: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1482(f,arguments.length,x0) }),
      _1483: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1483(f,arguments.length,x0) }),
      _1484: (x0,x1) => x0.removeChild(x1),
      _1489: Date.now,
      _1491: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1492: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1493: () => new Error().stack,
      _1494: () => typeof dartUseDateNowForTicks !== "undefined",
      _1495: () => 1000 * performance.now(),
      _1496: () => Date.now(),
      _1497: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1498: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1499: () => new WeakMap(),
      _1500: (map, o) => map.get(o),
      _1501: (map, o, v) => map.set(o, v),
      _1502: (exn) => exn.toString(),
      _1503: (exn) => exn.stack,
      _1504: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1505: x0 => new WeakRef(x0),
      _1506: x0 => x0.deref(),
      _1507: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1507(f,arguments.length,x0) }),
      _1508: x0 => new FinalizationRegistry(x0),
      _1509: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _1511: (x0,x1) => x0.unregister(x1),
      _1513: () => globalThis.WeakRef,
      _1514: () => globalThis.FinalizationRegistry,
      _1516: x0 => x0.call(),
      _1517: s => JSON.stringify(s),
      _1518: s => printToConsole(s),
      _1519: (o, p, r) => o.replaceAll(p, () => r),
      _1520: (o, p, r) => o.replace(p, () => r),
      _1521: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1522: s => s.toUpperCase(),
      _1523: s => s.trim(),
      _1524: s => s.trimLeft(),
      _1525: s => s.trimRight(),
      _1526: (string, times) => string.repeat(times),
      _1527: Function.prototype.call.bind(String.prototype.indexOf),
      _1528: (s, p, i) => s.lastIndexOf(p, i),
      _1529: (string, token) => string.split(token),
      _1530: Object.is,
      _1533: (o, t) => typeof o === t,
      _1534: (o, c) => o instanceof c,
      _1535: o => Object.keys(o),
      _1538: (o, a) => o + a,
      _1565: x0 => new Array(x0),
      _1567: x0 => x0.length,
      _1569: (x0,x1) => x0[x1],
      _1570: (x0,x1,x2) => { x0[x1] = x2 },
      _1573: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1575: x0 => new Int8Array(x0),
      _1576: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1578: x0 => new Uint8ClampedArray(x0),
      _1580: x0 => new Int16Array(x0),
      _1582: x0 => new Uint16Array(x0),
      _1584: x0 => new Int32Array(x0),
      _1586: x0 => new Uint32Array(x0),
      _1588: x0 => new Float32Array(x0),
      _1590: x0 => new Float64Array(x0),
      _1614: x0 => x0.random(),
      _1615: (x0,x1) => x0.getRandomValues(x1),
      _1616: () => globalThis.crypto,
      _1617: () => globalThis.Math,
      _1630: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1631: (handle) => clearTimeout(handle),
      _1632: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1633: (handle) => clearInterval(handle),
      _1634: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1635: () => Date.now(),
      _1636: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1637: (x0,x1) => x0.exec(x1),
      _1638: (x0,x1) => x0.test(x1),
      _1639: x0 => x0.pop(),
      _1641: o => o === undefined,
      _1643: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1645: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1646: o => o instanceof RegExp,
      _1647: (l, r) => l === r,
      _1648: o => o,
      _1649: o => o,
      _1650: o => o,
      _1651: b => !!b,
      _1652: o => o.length,
      _1654: (o, i) => o[i],
      _1655: f => f.dartFunction,
      _1656: () => ({}),
      _1657: () => [],
      _1659: () => globalThis,
      _1660: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1661: (o, p) => p in o,
      _1662: (o, p) => o[p],
      _1663: (o, p, v) => o[p] = v,
      _1664: (o, m, a) => o[m].apply(o, a),
      _1666: o => String(o),
      _1667: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1668: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1668(f,arguments.length,x0) }),
      _1669: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1669(f,arguments.length,x0,x1) }),
      _1670: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1671: o => [o],
      _1672: (o0, o1) => [o0, o1],
      _1673: (o0, o1, o2) => [o0, o1, o2],
      _1674: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1675: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1676: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1677: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1678: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI16ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1679: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1680: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1681: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1682: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1683: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1684: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1685: x0 => new ArrayBuffer(x0),
      _1686: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1687: x0 => x0.input,
      _1688: x0 => x0.index,
      _1689: x0 => x0.groups,
      _1690: x0 => x0.flags,
      _1691: x0 => x0.multiline,
      _1692: x0 => x0.ignoreCase,
      _1693: x0 => x0.unicode,
      _1694: x0 => x0.dotAll,
      _1695: (x0,x1) => { x0.lastIndex = x1 },
      _1696: (o, p) => p in o,
      _1697: (o, p) => o[p],
      _1698: (o, p, v) => o[p] = v,
      _1699: (o, p) => delete o[p],
      _1700: x0 => globalThis.Object.keys(x0),
      _1702: x0 => new Date(x0),
      _1704: x0 => x0.getTime(),
      _1705: x0 => x0.length,
      _1706: x0 => x0.message,
      _1707: x0 => x0.name,
      _1710: (x0,x1) => x0.update(x1),
      _1712: x0 => x0.continue(),
      _1727: (x0,x1) => x0.getKey(x1),
      _1730: x0 => x0.openKeyCursor(),
      _1737: (x0,x1,x2,x3) => x0.createIndex(x1,x2,x3),
      _1741: (x0,x1) => x0.get(x1),
      _1743: (x0,x1) => x0.put(x1),
      _1744: (x0,x1,x2) => x0.put(x1,x2),
      _1745: (x0,x1) => x0.delete(x1),
      _1746: (x0,x1) => x0.index(x1),
      _1748: (x0,x1) => x0.openCursor(x1),
      _1754: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1754(f,arguments.length,x0) }),
      _1755: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1755(f,arguments.length,x0) }),
      _1756: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1756(f,arguments.length,x0) }),
      _1757: (x0,x1) => x0.objectStore(x1),
      _1759: (x0,x1) => ({keyPath: x0,autoIncrement: x1}),
      _1760: (x0,x1,x2) => x0.createObjectStore(x1,x2),
      _1761: (x0,x1,x2) => x0.transaction(x1,x2),
      _1762: x0 => x0.close(),
      _1765: (x0,x1,x2) => x0.open(x1,x2),
      _1779: (x0,x1) => x0.item(x1),
      _1780: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1780(f,arguments.length,x0) }),
      _1781: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1781(f,arguments.length,x0) }),
      _1782: x0 => x0.arrayBuffer(),
      _1783: (x0,x1) => x0.sqlite3changeset_finalize(x1),
      _1784: (x0,x1) => x0.sqlite3session_delete(x1),
      _1785: (x0,x1) => x0.sqlite3_close_v2(x1),
      _1786: (x0,x1) => x0.sqlite3_finalize(x1),
      _1787: (x0,x1) => x0.dart_sqlite3_malloc(x1),
      _1788: (x0,x1) => x0.dart_sqlite3_free(x1),
      _1790: x0 => x0.sqlite3_initialize(),
      _1796: (x0,x1,x2,x3,x4) => x0.sqlite3_open_v2(x1,x2,x3,x4),
      _1797: (x0,x1) => x0.sqlite3_extended_errcode(x1),
      _1798: (x0,x1) => x0.sqlite3_errmsg(x1),
      _1799: (x0,x1) => x0.sqlite3_errstr(x1),
      _1800: (x0,x1) => x0.sqlite3_error_offset(x1),
      _1801: (x0,x1,x2) => x0.sqlite3_extended_result_codes(x1,x2),
      _1802: (x0,x1,x2) => x0.dart_sqlite3_updates(x1,x2),
      _1803: (x0,x1,x2) => x0.dart_sqlite3_commits(x1,x2),
      _1804: (x0,x1,x2) => x0.dart_sqlite3_rollbacks(x1,x2),
      _1805: (x0,x1,x2,x3,x4,x5) => x0.sqlite3_exec(x1,x2,x3,x4,x5),
      _1806: (x0,x1,x2,x3,x4,x5,x6) => x0.sqlite3_prepare_v3(x1,x2,x3,x4,x5,x6),
      _1807: (x0,x1) => x0.sqlite3_bind_parameter_count(x1),
      _1808: (x0,x1,x2) => x0.sqlite3_bind_null(x1,x2),
      _1809: (x0,x1,x2,x3) => x0.sqlite3_bind_int64(x1,x2,x3),
      _1810: (x0,x1,x2,x3) => x0.sqlite3_bind_double(x1,x2,x3),
      _1811: (x0,x1,x2,x3,x4) => x0.dart_sqlite3_bind_text(x1,x2,x3,x4),
      _1812: (x0,x1,x2,x3,x4) => x0.dart_sqlite3_bind_blob(x1,x2,x3,x4),
      _1814: (x0,x1) => x0.sqlite3_column_count(x1),
      _1815: (x0,x1,x2) => x0.sqlite3_column_name(x1,x2),
      _1816: (x0,x1,x2) => x0.sqlite3_column_type(x1,x2),
      _1817: (x0,x1,x2) => x0.sqlite3_column_int64(x1,x2),
      _1818: (x0,x1,x2) => x0.sqlite3_column_double(x1,x2),
      _1819: (x0,x1,x2) => x0.sqlite3_column_bytes(x1,x2),
      _1820: (x0,x1,x2) => x0.sqlite3_column_text(x1,x2),
      _1821: (x0,x1,x2) => x0.sqlite3_column_blob(x1,x2),
      _1838: (x0,x1) => x0.sqlite3_step(x1),
      _1839: (x0,x1) => x0.sqlite3_reset(x1),
      _1840: (x0,x1) => x0.sqlite3_changes(x1),
      _1843: (x0,x1) => x0.sqlite3_last_insert_rowid(x1),
      _1844: (x0,x1) => x0.sqlite3_get_autocommit(x1),
      _1845: (x0,x1,x2,x3) => x0.dart_sqlite3_db_config_int(x1,x2,x3),
      _1860: (x0,x1,x2,x3) => x0.dart_sqlite3_register_vfs(x1,x2,x3),
      _1865: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1865(f,arguments.length,x0) }),
      _1866: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1866(f,arguments.length,x0,x1) }),
      _1867: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1867(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1868: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1868(f,arguments.length,x0,x1,x2) }),
      _1869: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1869(f,arguments.length,x0,x1,x2,x3) }),
      _1870: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1870(f,arguments.length,x0,x1,x2,x3) }),
      _1871: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1871(f,arguments.length,x0,x1,x2) }),
      _1872: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1872(f,arguments.length,x0,x1) }),
      _1873: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1873(f,arguments.length,x0,x1) }),
      _1874: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1874(f,arguments.length,x0) }),
      _1875: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1875(f,arguments.length,x0,x1,x2,x3) }),
      _1876: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1876(f,arguments.length,x0,x1,x2,x3) }),
      _1877: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1877(f,arguments.length,x0,x1) }),
      _1878: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1878(f,arguments.length,x0,x1) }),
      _1879: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1879(f,arguments.length,x0,x1) }),
      _1880: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1880(f,arguments.length,x0,x1) }),
      _1881: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1881(f,arguments.length,x0,x1) }),
      _1882: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1882(f,arguments.length,x0,x1) }),
      _1883: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1883(f,arguments.length,x0) }),
      _1884: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1884(f,arguments.length,x0) }),
      _1885: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1885(f,arguments.length,x0) }),
      _1886: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1886(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1887: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1887(f,arguments.length,x0,x1,x2,x3) }),
      _1888: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1888(f,arguments.length,x0,x1,x2,x3) }),
      _1889: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1889(f,arguments.length,x0,x1,x2,x3) }),
      _1890: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1890(f,arguments.length,x0,x1) }),
      _1891: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1891(f,arguments.length,x0,x1) }),
      _1892: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1892(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1893: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1893(f,arguments.length,x0,x1) }),
      _1894: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1894(f,arguments.length,x0,x1) }),
      _1895: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1895(f,arguments.length,x0,x1,x2) }),
      _1896: (x0,x1,x2) => x0.instantiateStreaming(x1,x2),
      _1900: x0 => new URL(x0),
      _1901: (x0,x1) => new URL(x0,x1),
      _1902: (x0,x1) => globalThis.fetch(x0,x1),
      _1903: (x0,x1,x2) => x0.postMessage(x1,x2),
      _1905: (x0,x1) => x0.error(x1),
      _1906: (x0,x1) => new SharedWorker(x0,x1),
      _1907: x0 => new Worker(x0),
      _1908: () => new MessageChannel(),
      _1909: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1909(f,arguments.length,x0) }),
      _1910: (x0,x1,x2) => x0.postMessage(x1,x2),
      _1911: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1911(f,arguments.length,x0) }),
      _1912: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1912(f,arguments.length,x0) }),
      _1925: (x0,x1) => globalThis.IDBKeyRange.bound(x0,x1),
      _1926: x0 => ({autoIncrement: x0}),
      _1927: x0 => ({unique: x0}),
      _1928: (x0,x1) => x0.createObjectStore(x1),
      _1929: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1929(f,arguments.length,x0) }),
      _1930: (x0,x1) => ({name: x0,length: x1}),
      _1931: x0 => globalThis.IDBKeyRange.only(x0),
      _1933: x0 => x0.name,
      _1934: x0 => x0.length,
      _1939: () => globalThis.indexedDB,
      _1952: x0 => globalThis.BigInt(x0),
      _1953: x0 => globalThis.Number(x0),
      _1972: x0 => globalThis.Object.keys(x0),
      _1973: x0 => x0.length,
      _1974: () => new XMLHttpRequest(),
      _1975: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1977: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1978: (x0,x1) => x0.send(x1),
      _1979: x0 => x0.send(),
      _1981: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1981(f,arguments.length,x0) }),
      _1982: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1982(f,arguments.length,x0) }),
      _1990: (x0,x1) => new WebSocket(x0,x1),
      _1991: (x0,x1) => x0.send(x1),
      _1992: (x0,x1,x2) => x0.close(x1,x2),
      _1993: (x0,x1) => x0.close(x1),
      _1994: x0 => x0.close(),
      _1995: (x0,x1) => x0.item(x1),
      _1997: (x0,x1,x2) => x0.open(x1,x2),
      _1998: x0 => x0.abort(),
      _1999: x0 => x0.getAllResponseHeaders(),
      _2000: (x0,x1) => x0.append(x1),
      _2001: () => new AbortController(),
      _2002: x0 => x0.abort(),
      _2003: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _2004: (x0,x1) => globalThis.fetch(x0,x1),
      _2005: (x0,x1) => x0.get(x1),
      _2006: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._2006(f,arguments.length,x0,x1,x2) }),
      _2007: (x0,x1) => x0.forEach(x1),
      _2008: x0 => x0.getReader(),
      _2009: x0 => x0.cancel(),
      _2010: x0 => x0.read(),
      _2011: x0 => x0.trustedTypes,
      _2012: (x0,x1) => { x0.src = x1 },
      _2013: (x0,x1) => x0.createScriptURL(x1),
      _2014: x0 => x0.nonce,
      _2015: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2015(f,arguments.length,x0) }),
      _2016: x0 => ({createScriptURL: x0}),
      _2017: (x0,x1) => x0.querySelectorAll(x1),
      _2018: (x0,x1) => x0.key(x1),
      _2019: x0 => x0.trustedTypes,
      _2020: (x0,x1) => { x0.text = x1 },
      _2021: o => o instanceof Array,
      _2022: (a, i) => a.push(i),
      _2023: (a, i) => a.splice(i, 1)[0],
      _2025: (a, l) => a.length = l,
      _2026: a => a.pop(),
      _2027: (a, i) => a.splice(i, 1),
      _2028: (a, s) => a.join(s),
      _2029: (a, s, e) => a.slice(s, e),
      _2031: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _2032: a => a.length,
      _2033: (a, l) => a.length = l,
      _2034: (a, i) => a[i],
      _2035: (a, i, v) => a[i] = v,
      _2037: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _2038: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _2040: o => o instanceof Uint8Array,
      _2041: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _2042: o => o instanceof Int8Array,
      _2043: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _2044: o => o instanceof Uint8ClampedArray,
      _2045: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _2046: o => o instanceof Uint16Array,
      _2047: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _2048: o => o instanceof Int16Array,
      _2049: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _2050: o => o instanceof Uint32Array,
      _2051: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _2052: o => o instanceof Int32Array,
      _2053: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _2055: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _2056: o => o instanceof Float32Array,
      _2057: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _2058: o => o instanceof Float64Array,
      _2059: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _2060: (t, s) => t.set(s),
      _2061: l => new DataView(new ArrayBuffer(l)),
      _2062: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _2063: o => o.byteLength,
      _2064: o => o.buffer,
      _2065: o => o.byteOffset,
      _2066: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _2067: (b, o) => new DataView(b, o),
      _2068: (b, o, l) => new DataView(b, o, l),
      _2069: Function.prototype.call.bind(DataView.prototype.getUint8),
      _2070: Function.prototype.call.bind(DataView.prototype.setUint8),
      _2071: Function.prototype.call.bind(DataView.prototype.getInt8),
      _2072: Function.prototype.call.bind(DataView.prototype.setInt8),
      _2073: Function.prototype.call.bind(DataView.prototype.getUint16),
      _2074: Function.prototype.call.bind(DataView.prototype.setUint16),
      _2075: Function.prototype.call.bind(DataView.prototype.getInt16),
      _2076: Function.prototype.call.bind(DataView.prototype.setInt16),
      _2077: Function.prototype.call.bind(DataView.prototype.getUint32),
      _2078: Function.prototype.call.bind(DataView.prototype.setUint32),
      _2079: Function.prototype.call.bind(DataView.prototype.getInt32),
      _2080: Function.prototype.call.bind(DataView.prototype.setInt32),
      _2083: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _2084: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _2085: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _2086: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _2087: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _2088: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _2089: Function.prototype.call.bind(Number.prototype.toString),
      _2090: Function.prototype.call.bind(BigInt.prototype.toString),
      _2091: Function.prototype.call.bind(Number.prototype.toString),
      _2092: (d, digits) => d.toFixed(digits),
      _2098: (x0,x1) => x0.getContext(x1),
      _2103: () => globalThis.document,
      _2109: (x0,x1) => { x0.height = x1 },
      _2111: (x0,x1) => { x0.width = x1 },
      _2113: (x0,x1) => { x0.pointerEvents = x1 },
      _2122: x0 => x0.style,
      _2125: x0 => x0.src,
      _2126: (x0,x1) => { x0.src = x1 },
      _2127: x0 => x0.naturalWidth,
      _2128: x0 => x0.naturalHeight,
      _2144: x0 => x0.status,
      _2145: (x0,x1) => { x0.responseType = x1 },
      _2147: x0 => x0.response,
      _2148: () => globalThis.google.accounts.oauth2,
      _2153: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2153(f,arguments.length,x0) }),
      _2154: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2154(f,arguments.length,x0) }),
      _2155: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12) => ({client_id: x0,scope: x1,include_granted_scopes: x2,redirect_uri: x3,callback: x4,state: x5,enable_granular_consent: x6,enable_serial_consent: x7,login_hint: x8,hd: x9,ux_mode: x10,select_account: x11,error_callback: x12}),
      _2156: x0 => x0.code,
      _2159: x0 => x0.error,
      _2162: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2162(f,arguments.length,x0) }),
      _2163: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2163(f,arguments.length,x0) }),
      _2164: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10) => ({client_id: x0,callback: x1,scope: x2,include_granted_scopes: x3,prompt: x4,enable_granular_consent: x5,enable_serial_consent: x6,login_hint: x7,hd: x8,state: x9,error_callback: x10}),
      _2168: x0 => x0.access_token,
      _2169: x0 => x0.expires_in,
      _2175: x0 => x0.error,
      _2178: x0 => x0.type,
      _2183: () => globalThis.google.accounts.id,
      _2188: (x0,x1) => x0.renderButton(x1),
      _2189: (x0,x1,x2) => x0.renderButton(x1,x2),
      _2197: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2197(f,arguments.length,x0) }),
      _2200: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16) => ({client_id: x0,auto_select: x1,callback: x2,login_uri: x3,native_callback: x4,cancel_on_tap_outside: x5,prompt_parent_id: x6,nonce: x7,context: x8,state_cookie_domain: x9,ux_mode: x10,allowed_parent_origin: x11,intermediate_iframe_close_callback: x12,itp_support: x13,login_hint: x14,hd: x15,use_fedcm_for_prompt: x16}),
      _2211: x0 => x0.error,
      _2213: x0 => x0.credential,
      _2216: (x0,x1,x2,x3,x4,x5,x6,x7,x8) => ({type: x0,theme: x1,size: x2,text: x3,shape: x4,logo_alignment: x5,width: x6,locale: x7,click_listener: x8}),
      _2224: x0 => { globalThis.onGoogleLibraryLoad = x0 },
      _2225: (module,f) => finalizeWrapper(f, function() { return module.exports._2225(f,arguments.length) }),
      _2263: x0 => x0.readyState,
      _2265: (x0,x1) => { x0.timeout = x1 },
      _2267: (x0,x1) => { x0.withCredentials = x1 },
      _2268: x0 => x0.upload,
      _2269: x0 => x0.responseURL,
      _2270: x0 => x0.status,
      _2271: x0 => x0.statusText,
      _2273: (x0,x1) => { x0.responseType = x1 },
      _2274: x0 => x0.response,
      _2286: x0 => x0.loaded,
      _2287: x0 => x0.total,
      _2310: x0 => x0.length,
      _2333: (x0,x1) => { x0.draggable = x1 },
      _2349: x0 => x0.style,
      _2362: (x0,x1) => { x0.oncancel = x1 },
      _2368: (x0,x1) => { x0.onchange = x1 },
      _2408: (x0,x1) => { x0.onerror = x1 },
      _2548: (x0,x1) => { x0.nonce = x1 },
      _2708: (x0,x1) => { x0.download = x1 },
      _2733: (x0,x1) => { x0.href = x1 },
      _2781: (x0,x1) => { x0.src = x1 },
      _2792: x0 => x0.width,
      _2794: x0 => x0.height,
      _2826: (x0,x1) => { x0.src = x1 },
      _2952: x0 => x0.error,
      _2954: (x0,x1) => { x0.src = x1 },
      _2959: (x0,x1) => { x0.crossOrigin = x1 },
      _2962: (x0,x1) => { x0.preload = x1 },
      _2966: x0 => x0.currentTime,
      _2967: (x0,x1) => { x0.currentTime = x1 },
      _2968: x0 => x0.duration,
      _2973: (x0,x1) => { x0.playbackRate = x1 },
      _2982: (x0,x1) => { x0.loop = x1 },
      _2986: (x0,x1) => { x0.volume = x1 },
      _3003: x0 => x0.code,
      _3004: x0 => x0.message,
      _3275: (x0,x1) => { x0.accept = x1 },
      _3289: x0 => x0.files,
      _3315: (x0,x1) => { x0.multiple = x1 },
      _3333: (x0,x1) => { x0.type = x1 },
      _3583: (x0,x1) => { x0.src = x1 },
      _3585: (x0,x1) => { x0.type = x1 },
      _3589: (x0,x1) => { x0.async = x1 },
      _3591: (x0,x1) => { x0.defer = x1 },
      _3593: (x0,x1) => { x0.crossOrigin = x1 },
      _3595: (x0,x1) => { x0.text = x1 },
      _3603: (x0,x1) => { x0.charset = x1 },
      _3627: x0 => x0.width,
      _3628: (x0,x1) => { x0.width = x1 },
      _3629: x0 => x0.height,
      _3630: (x0,x1) => { x0.height = x1 },
      _4051: () => globalThis.window,
      _4091: x0 => x0.document,
      _4113: x0 => x0.navigator,
      _4370: x0 => x0.indexedDB,
      _4375: x0 => x0.trustedTypes,
      _4376: x0 => x0.sessionStorage,
      _4377: x0 => x0.localStorage,
      _4481: x0 => x0.geolocation,
      _4484: x0 => x0.mediaDevices,
      _4486: x0 => x0.permissions,
      _4500: x0 => x0.userAgent,
      _4501: x0 => x0.vendor,
      _4506: x0 => x0.onLine,
      _4551: x0 => x0.data,
      _4552: x0 => x0.origin,
      _4581: x0 => x0.port1,
      _4582: x0 => x0.port2,
      _4586: (x0,x1) => { x0.onmessage = x1 },
      _4661: (x0,x1) => { x0.onerror = x1 },
      _4669: x0 => x0.port,
      _4671: (x0,x1) => { x0.onerror = x1 },
      _4704: x0 => x0.length,
      _4921: x0 => x0.readyState,
      _4934: (x0,x1) => { x0.binaryType = x1 },
      _4937: x0 => x0.code,
      _4938: x0 => x0.reason,
      _6088: x0 => x0.destination,
      _6092: x0 => x0.state,
      _6093: x0 => x0.audioWorklet,
      _6195: (x0,x1) => { x0.fftSize = x1 },
      _6196: x0 => x0.frequencyBinCount,
      _6198: (x0,x1) => { x0.minDecibels = x1 },
      _6200: (x0,x1) => { x0.maxDecibels = x1 },
      _6202: (x0,x1) => { x0.smoothingTimeConstant = x1 },
      _6456: x0 => x0.port,
      _6595: x0 => x0.type,
      _6596: x0 => x0.target,
      _6636: x0 => x0.signal,
      _6645: x0 => x0.length,
      _6647: x0 => x0.length,
      _6666: x0 => x0.addedNodes,
      _6693: x0 => x0.firstChild,
      _6704: () => globalThis.document,
      _6784: x0 => x0.body,
      _6786: x0 => x0.head,
      _7114: x0 => x0.id,
      _7115: (x0,x1) => { x0.id = x1 },
      _7142: x0 => x0.children,
      _8461: x0 => x0.value,
      _8463: x0 => x0.done,
      _8627: x0 => x0.size,
      _8628: x0 => x0.type,
      _8631: (x0,x1) => { x0.type = x1 },
      _8634: x0 => x0.name,
      _8635: x0 => x0.lastModified,
      _8640: x0 => x0.length,
      _8645: x0 => x0.result,
      _9014: x0 => x0.mimeType,
      _9015: x0 => x0.state,
      _9019: (x0,x1) => { x0.onstop = x1 },
      _9021: (x0,x1) => { x0.ondataavailable = x1 },
      _9046: x0 => x0.data,
      _9135: x0 => x0.url,
      _9137: x0 => x0.status,
      _9139: x0 => x0.statusText,
      _9140: x0 => x0.headers,
      _9141: x0 => x0.body,
      _9153: x0 => x0.instance,
      _9155: () => globalThis.WebAssembly,
      _9177: x0 => x0.exports,
      _9185: x0 => x0.buffer,
      _9499: x0 => x0.contentRect,
      _9925: x0 => x0.active,
      _10184: x0 => x0.sampleRate,
      _10196: x0 => x0.channelCount,
      _10586: x0 => x0.result,
      _10587: x0 => x0.error,
      _10592: (x0,x1) => { x0.onsuccess = x1 },
      _10594: (x0,x1) => { x0.onerror = x1 },
      _10598: (x0,x1) => { x0.onupgradeneeded = x1 },
      _10600: x0 => x0.oldVersion,
      _10613: x0 => x0.name,
      _10615: x0 => x0.objectStoreNames,
      _10632: x0 => x0.name,
      _10634: x0 => x0.keyPath,
      _10637: x0 => x0.autoIncrement,
      _10656: x0 => x0.key,
      _10657: x0 => x0.primaryKey,
      _10659: x0 => x0.value,
      _10665: x0 => x0.error,
      _10667: (x0,x1) => { x0.onabort = x1 },
      _10669: (x0,x1) => { x0.oncomplete = x1 },
      _10671: (x0,x1) => { x0.onerror = x1 },
      _11497: (x0,x1) => { x0.display = x1 },
      _12719: x0 => x0.name,
      _12720: x0 => x0.message,
      _13049: x0 => x0.width,
      _13050: x0 => x0.height,
      _13434: () => globalThis.console,
      _13455: x0 => globalThis.getWhatsUnityFCMToken(x0),
      _13460: x0 => x0.name,
      _13461: x0 => x0.message,
      _13462: x0 => x0.code,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
